### ISSUE TITLE
WebUI enabled?

### ISSUE THREAD

**Issue by kishansundar** [rodeodomino/algo-pihole#14]

**Comment by rodeodomino** [comment]
Not sure I understand your question, but if you're talking about Pi-hole, then yes, it's enabled.

You can change the installation settings in the [setupVars.conf file](https://github.com/rodeodomino/algo-pihole/blob/master/roles/pihole/templates/setupVars.conf.j2)

**Comment by kishansundar** [comment]
yes I am talking about pihole. Thank you
