### ISSUE TITLE
Wireguard. Error bringing up tunnel. bad address

### ISSUE THREAD

**Issue by whisperdancer** [rodeodomino/algo-pihole#19]
**Describe the bug**

**To Reproduce**

1. Scan QR code of phone-pihole user
2. Try to connect to vpn by flipping the on switch
3. ..

**Expected behavior**

I expect to be connected to the tunnel. Note, works fine for phone-full. The error happens with the phone-phole user. So I can connect successfully with phone-full user, but error with phone-pihole user.

It would also be helpful if you could explain the difference between the two users and what would be an applicable use case for using one over the other. Thank you!!

**Comment by rodeodomino** [comment]
I can't duplicate this either. What is the content of the phone-pihole.conf?

full means that all data goes through the tunnel. pihole is just dns requests for pihole ad blocking.

**Comment by whisperdancer** [comment]
Sorry to trouble you. Not a bug. I had two vpn's running and that caused the issue. Closing.

**Comment by ProustIdee** [comment]
I'm having this same issue. I removed OpenVPN from my phone and restarted it. There is no other VPN other than Wireguard.

Works fine with "phone-full" config, gives "Error bringing up tunnel: Bad Address" with the "phone-pihole" config.

**Comment by cmersinli** [comment]
+1
