### ISSUE TITLE
Custom DNS Server?

### ISSUE THREAD

**Issue by whisperdancer** [rodeodomino/algo-pihole#20]
Not a bug, but a question. Noticed pihole DNS is set to Custom 1 with IP-of-pihole#5353

I have another pihole setup on my local lan and use unbound and my DNS has same setting. You are not using unbound because I tracked the DNS to Cloudflare.  Can you please explain how this is setup in pihole? Is it using Cloudflared? Thank you

**Comment by rodeodomino** [comment]
This uses dnscrypt-proxy. It’s just a fork of https://github.com/trailofbits/algo, where I swap out dnsmasq with Pihole
