### ISSUE TITLE
pihole and firewall

### ISSUE THREAD

**Issue by whisperdancer** [rodeodomino/algo-pihole#21]
First, thank you again for the great work on this project! 

I have a question regarding the phile web interface and firewall.

https://docs.pi-hole.net/guides/vpn/firewall/

In addition to the risk of being an open resolver, your Web interface is also open to the world increasing the risk. So you will want to prevent ports 53 and 80, respectively, from being accessible from the public Internet.

The pihole docs disallow the pihole web ui from being accessed from the internet. It is only accessible when connected to the vpn. They do this with firewall rules.

Does your fork to include pihole implement this security feature also?
Thank you!

**Comment by rodeodomino** [comment]
There's a firewall created in https://github.com/rodeodomino/algo-pihole/blob/master/roles/common/tasks/iptables.yml using https://github.com/rodeodomino/algo-pihole/blob/master/roles/common/templates/rules.v4.j2 and https://github.com/rodeodomino/algo-pihole/blob/master/roles/common/templates/rules.v6.j2

it's all just built off https://github.com/trailofbits/algo with a couple tweaks for Pihole.

**Comment by markitosgv** [comment]
A question about this, is it possible to make DNS server public? I trying to add this rule to firewall:

iptables -A INPUT -d publicserverip/32 -p udp -m udp --dport 53 -j ACCEPT

But this doesn't work from a PC outside VPN

**Comment by rodeodomino** [comment]
Nope, a pi-hole left open like that creates an open resolver, which aids in DNS Amplification Attacks

From here: https://docs.pi-hole.net/guides/vpn/overview/

**Comment by markitosgv** [comment]
thanks!
