### ISSUE TITLE
Out of Memory Error

### ISSUE THREAD

**Issue by whisperdancer** [rodeodomino/algo-pihole#22]
Installed all the prerequisites and run algo. Earlier when I run your fork all went fine. Now, I had to create a new instance and whenever I run ./algo near the end I continually get this error:

TASK [pihole : Run gravityOptimise] ********************************************
fatal: [35.161.177.207]: FAILED! => {"changed": true, "cmd": ["/usr/local/bin/gravityOptimise.sh"], "delta": "0:00:20.453394", "end": "2019-06-17 22:06:45.787518", "msg": "non-zero return code", "rc": 254, "start": "2019-06-17 22:06:25.334124", "stderr": "/usr/local/bin/gravityOptimise.sh: fork: Cannot allocate memory", "stderr_lines": ["/usr/local/bin/gravityOptimise.sh: fork: Cannot allocate memory"], "stdout": "[i] Updating gravity\n[i] Parsing existing wildcard config (DNSMASQ)\n[i] Removing wildcard matches from gravity\n[i] Removing regex matches from gravity\n[i] Updating gravity database", "stdout_lines": ["[i] Updating gravity", "[i] Parsing existing wildcard config (DNSMASQ)", "[i] Removing wildcard matches from gravity", "[i] Removing regex matches from gravity", "[i] Updating gravity database"]}
included: /home/ubuntu/algo-pihole/playbooks/rescue.yml for 35.161.177.207

TASK [pihole : debug] **********************************************************
ok: [35.161.177.207] => {
    "fail_hint": [
        "Sorry, but something went wrong!",
        "Please check the troubleshooting guide.",
        "https://trailofbits.github.io/algo/troubleshooting.html"
    ]
}

TASK [pihole : Fail the installation] ******************************************
fatal: [35.161.177.207]: FAILED! => {"changed": false, "msg": "Failed as requested from task"}
included: /home/ubuntu/algo-pihole/playbooks/rescue.yml for 35.161.177.207

TASK [debug] *******************************************************************
ok: [35.161.177.207] => {
    "fail_hint": [
        "Sorry, but something went wrong!",
        "Please check the troubleshooting guide.",
        "https://trailofbits.github.io/algo/troubleshooting.html"
    ]
}

TASK [Fail the installation] ***************************************************
fatal: [35.161.177.207]: FAILED! => {"changed": false, "msg": "Failed as requested from task"}

PLAY RECAP *********************************************************************
35.161.177.207             : ok=63   changed=40   unreachable=0    failed=3
localhost                  : ok=36   changed=8    unreachable=0    failed=0

**Comment by rodeodomino** [comment]
What service are you using?

**Comment by whisperdancer** [comment]
I"m running aldo installer on raspberry pi 3 and installing to Amazon Lightsail

**Comment by rodeodomino** [comment]
A few of the default providers don't offer enough RAM to run that script (Google Cloud, Lightsail, openstack). I'll have to remove that feature completely so it works across. In the meantime, you can comment out running it from `roles/pihole/tasks/wildcards.yml`
