### ISSUE TITLE
Using Algo with Unbound?

### ISSUE THREAD

**Issue by whisperdancer** [rodeodomino/algo-pihole#25]
First, a big thank you for all your hard work. Your fork is fantastic. Unfortunately, IMHO it falls a bit short of the most secure solution. 

I ask you this because it's beyond my technical abilities to do it. Is it possible to replace the dnscrypt code with unbound on the backend for pihole. I don't know how much work it would be. I tried to simply add unbound to the algo server, but it fails to start. I surmise it's due to some sort of conflict with port 53.

https://docs.pi-hole.net/guides/unbound/
https://www.reddit.com/r/pihole/comments/9nkjzz/dnscryptproxy_vs_cloudflared_vs_unbound/

I currently have a VPN setup using OpenVpn and Pihole and I use unbound as the resolver. It's great. My goal is to do the same thing with Algo and pihole. 

Would love to get your thoughts on this and if you think it's a viable option or replacement for the current dnscrypt to cloudflare. I know a few of the pihole devs have chosen to go with the unbound solution over dnscrypt.

Thanks again.

**Comment by rodeodomino** [comment]
This is merely a fork of Algo, so it uses what they use.

You can set `dns_encryption` to `false` in `config.cfg` and it won't install dnscrypt-proxy. It shouldn't break anything, but YMMV.
