### ISSUE TITLE
DNS Client setting points to pihole upstream IP rather than pihole IP

### ISSUE THREAD

**Issue by whisperdancer** [rodeodomino/algo-pihole#32]
The internal IP of my server is ip-172-20-31-42 which is what I see when I navigate to pihole web interface. I select settings/dns and upstream DNS is set to 172.20.162.148#5353

I noticed in my interface for my client the following settings. I would think the DNS should point to the pihole IP which is the internal IP of the server 172-20-31-42. Then pihole will do its ad blocking and forward upstream DNS to 172.20.162.148. However, the DNS is set to the upstream forwarded address rather than the pihole IP address.

[Interface]
PrivateKey = <priv_key>
Address = 10.21.44.3/24
DNS = 172.20.162.148  ( shouldn't this value be the pihole IP, rather than the upstream IP? )

**Comment by rodeodomino** [comment]
Algo creates a new localhost IP address that it uses for all services (dns, wireguard, strongswan). This follows the same convention
